name: Publish Image

on:
  workflow_run:
    workflows: ["Backend Tests", "Browser Tests"]
    types:
      - completed

jobs:
  run_after_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}
          push: true
