name: Publish Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run backend tests
        run: ./node_modules/.bin/mocha -r dotenv/config --exit -t 5000

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define env variables
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}

      - name: Publish image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          tags: ghcr.io/${{ env.REPOSITORY }}
          push: true
